//tests.tup,tests.dependencies,tests.simple_foo_reggaefile,tests.code_command,tests.options,tests.simple_bar_reggaefile,tests.ninja,tests.default_rules,tests.cpprules,tests.ut,tests.binary,tests.by_package,tests.realistic_build,tests.drules,tests.high_rules,tests.range,tests.dub_json,tests.dub_call,tests.reflect,tests.build,tests.json_build.rules,tests.json_build.simple,tests.make,tests.ctaa
//Automatically generated by dtest, do not edit by hand
import unit_threaded.runner;
import std.stdio;

int main(string[] args) {
    writeln("\nAutomatically generated file tests/ut.d");
    writeln(`Running unit tests from dirs ["tests"]`);
    return args.runTests!(
                          "tests.tup",
                          "tests.dependencies",
                          "tests.simple_foo_reggaefile",
                          "tests.code_command",
                          "tests.simple_bar_reggaefile",
                          "tests.ninja",
                          "tests.default_rules",
                          "tests.cpprules",
                          "tests.binary",
                          "tests.by_package",
                          "tests.realistic_build",
                          "tests.drules",
                          "tests.high_rules",
                          "tests.range",
                          "tests.dub_json",
                          "tests.dub_call",
                          "tests.reflect",
                          "tests.build",
                          "tests.json_build.rules",
                          "tests.json_build.simple",
                          "tests.make",
                          "tests.ctaa"
                          );
}
