//tests.json_build.simple,tests.json_build.rules,tests.reflect,tests.by_package,tests.make,tests.simple_foo_reggaefile,tests.tup,tests.ninja,tests.binary,tests.code_command,tests.serialisation,tests.dependencies,tests.cpprules,tests.default_options,tests.dub_json,tests.default_rules,tests.ctaa,tests.drules,tests.dub_call,tests.range,tests.realistic_build,tests.build,tests.high_rules,tests.simple_bar_reggaefile
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args)
{
    writeln("\nAutomatically generated file tests/ut.d");
    writeln(`Running unit tests from dirs ["tests"]`);
    return runTests!(
                     "tests.json_build.simple",
                     "tests.json_build.rules",
                     "tests.reflect",
                     "tests.by_package",
                     "tests.make",
                     "tests.simple_foo_reggaefile",
                     "tests.tup",
                     "tests.ninja",
                     "tests.binary",
                     "tests.code_command",
                     "tests.serialisation",
                     "tests.dependencies",
                     "tests.cpprules",
                     "tests.default_options",
                     "tests.dub_json",
                     "tests.default_rules",
                     "tests.ctaa",
                     "tests.drules",
                     "tests.dub_call",
                     "tests.range",
                     "tests.realistic_build",
                     "tests.build",
                     "tests.high_rules",
                     "tests.simple_bar_reggaefile"
                     )
                     (args);
}
