module tests.ut.make;

import unit_threaded;
import reggae;


void testMakefileNoPath() {
    auto build = Build(Target("leapp",
                               "dmd -ofleapp objs/leapp.objs/foo.o objs/leapp.objs/bar.o",
                               [Target("foo.o", "dmd -c -ofobjs/leapp.objs/foo.o foo.d", [Target("foo.d")]),
                                Target("bar.o", "dmd -c -ofobjs/leapp.objs/bar.o bar.d", [Target("bar.d")])],
                            ));
    auto backend = Makefile(build);
    backend.fileName.shouldEqual("Makefile");
    backend.simpleOutput.shouldEqual(
        "# Automatically generated by reggae version " ~ version_ ~ "\n"
        "# Do not edit by hand\n"
        "all: leapp\n"
        ".SUFFIXES:\n"
        "CC = \n"
        "CXX = \n"
        "DC = \n"
        "objs/leapp.objs/foo.o: foo.d Makefile\n"
        "\tdmd -c -ofobjs/leapp.objs/foo.o foo.d\n"
        "objs/leapp.objs/bar.o: bar.d Makefile\n"
        "\tdmd -c -ofobjs/leapp.objs/bar.o bar.d\n"
        "leapp: objs/leapp.objs/foo.o objs/leapp.objs/bar.o Makefile\n"
        "\tdmd -ofleapp objs/leapp.objs/foo.o objs/leapp.objs/bar.o\n"
        );
}


void testMakefilePath() {
    auto build = Build(Target("otherapp",
                               "gcc -o $out $in",
                               [Target("boo.o", "gcc -c -o $out $in", [Target("boo.c")]),
                                Target("baz.o", "gcc -c -o $out $in", [Target("baz.c")])],
                            ));
    auto backend = Makefile(build, "/global/path/to/");
    backend.fileName.shouldEqual("Makefile");
    backend.simpleOutput.shouldEqual(
        "# Automatically generated by reggae version " ~ version_ ~ "\n"
        "# Do not edit by hand\n"
        "all: otherapp\n"
        ".SUFFIXES:\n"
        "CC = gcc\n"
        "CXX = g++\n"
        "DC = dmd\n"
        "objs/otherapp.objs/boo.o: /global/path/to/boo.c Makefile\n"
        "\t$(CC) -c -o objs/otherapp.objs/boo.o /global/path/to/boo.c\n"
        "objs/otherapp.objs/baz.o: /global/path/to/baz.c Makefile\n"
        "\t$(CC) -c -o objs/otherapp.objs/baz.o /global/path/to/baz.c\n"
        "otherapp: objs/otherapp.objs/boo.o objs/otherapp.objs/baz.o Makefile\n"
        "\t$(CC) -o otherapp objs/otherapp.objs/boo.o objs/otherapp.objs/baz.o\n"
        );
}


void testImplicitDependencies() {
    auto target = Target("foo.o", "gcc -o $out -c $in", [Target("foo.c")], [Target("foo.h")]);
    auto make = Makefile(Build(target));
    make.simpleOutput.shouldEqual(
        "# Automatically generated by reggae version " ~ version_ ~ "\n"
        "# Do not edit by hand\n"
        "all: foo.o\n"
        ".SUFFIXES:\n"
        "CC = \n"
        "CXX = \n"
        "DC = \n"
        "foo.o: foo.c foo.h Makefile\n"
        "\tgcc -o foo.o -c foo.c\n"
        );
}
